name: CI

on: [pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: baijunyao/mysql
        env:
          MYSQL_ROOT_PASSWORD: laravel_bjyblog
          MYSQL_DATABASE: laravel_bjyblog
    container:
      image: baijunyao/php:local
      volumes:
        - .:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
          php artisan key:generate
          php artisan passport:keys
          php artisan migrate
          php artisan db:seed
      - name: Code Style
        run: |
          ./vendor/bin/php-cs-fixer fix --verbose --show-progress=dots
      - name: PHPStan
        run: |
          ./vendor/bin/phpstan analyse --ansi
      - name: Test
        run: |
          ./vendor/bin/phpunit
